apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  
spec:
  selector:
    matchLabels:
      app: test-app
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: REPOSITORY_TAG
        resources:
          requests:
             memory: 50Mi
             cpu: 0.25

---
apiVersion: v1
kind: Service
metadata:
  name: test-app-svc

spec:
  selector:
    app: test-app

  ports:
    - name: http
      port: 80

  type: LoadBalancer
