name: Deploy to EKS

on: push

jobs:
  loginToAWS:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

  buildImage-and-Push-to-ECR:
    runs-on: ubuntu-latest
    needs:
      loginToAWS

    steps:
    - name: Code Checkout
      uses: actions/checkout@v4

    - name: Login to AWSECR
      uses: docker/login-action@v3
      with:
        registry: 585853585762.dkr.ecr.sa-east-1.amazonaws.com
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      env:
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build and Push NGINX Image
      env:
        REGISTRY: 585853585762.dkr.ecr.sa-east-1.amazonaws.com
        REPO: nginx
        REPOSITORY_TAG: ${REGISTRY}/${REPO}:${GITHUB_RUN_NUMBER}
      run: |
        # Build the Docker image using the multi-stage Dockerfile
        docker build -t nginx .
        
        # Tag and push the NGINX image to ECR
        docker tag nginx:latest ${REGISTRY}/${REPO}:${GITHUB_RUN_NUMBER}
        docker push ${REGISTRY}/${REPO}:${GITHUB_RUN_NUMBER}

  install_Kubectl:
    runs-on: ubuntu-latest

    steps:
    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    needs:
      buildImage-and-Push-to-ECR

  deployToCluster:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Configure kubectl
      env:
        KUBECONFIG: ${{ runner.temp }}/kubeconfig
      run: |
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }} --kubeconfig $KUBECONFIG
        echo "KUBECONFIG=$KUBECONFIG" >> $GITHUB_ENV

    - name: Deploy to EKS
      run: |
        sed -i "s|image: REPOSITORY_TAG|image: 585853585762.dkr.ecr.sa-east-1.amazonaws.com/nginx:$GITHUB_RUN_NUMBER|g" ./deploy.yaml
        kubectl apply -f ./deploy.yaml

    needs:
      install_Kubectl
